/*
 * 六合彩号码盘种子：4 类统计 × 49 号码
 * 特码 47 / 特肖 11 / 平特 7.8 / 平码 8.07
 */
SET NAMES utf8mb4;

-- 清理旧演示类目参数（保留已有账单不受影响）
DELETE FROM `fa_acc_user_price` WHERE `category_id` IN (1, 2, 3, 4);
DELETE FROM `fa_acc_param` WHERE `category_id` IN (1, 2, 3, 4);
DELETE FROM `fa_acc_category` WHERE `id` IN (1, 2, 3, 4);

INSERT INTO `fa_acc_category` (`id`, `name`, `code`, `icon`, `weigh`, `status`, `createtime`, `updatetime`) VALUES
(1, '特码', 'tema', '', 100, 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(2, '特肖', 'texiao', '', 90, 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(3, '平特', 'pingte', '', 80, 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()),
(4, '平码', 'pingma', '', 70, 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());

-- 特码 赔率 47，号码 01-49
INSERT INTO `fa_acc_param` (`category_id`, `name`, `default_price`, `unit`, `weigh`, `status`, `createtime`, `updatetime`)
SELECT 1, LPAD(n, 2, '0'), 47.0000, '注', 50 - n, 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()
FROM (
  SELECT 1 n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10
  UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20
  UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25 UNION SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29 UNION SELECT 30
  UNION SELECT 31 UNION SELECT 32 UNION SELECT 33 UNION SELECT 34 UNION SELECT 35 UNION SELECT 36 UNION SELECT 37 UNION SELECT 38 UNION SELECT 39 UNION SELECT 40
  UNION SELECT 41 UNION SELECT 42 UNION SELECT 43 UNION SELECT 44 UNION SELECT 45 UNION SELECT 46 UNION SELECT 47 UNION SELECT 48 UNION SELECT 49
) t;

-- 特肖 赔率 11
INSERT INTO `fa_acc_param` (`category_id`, `name`, `default_price`, `unit`, `weigh`, `status`, `createtime`, `updatetime`)
SELECT 2, LPAD(n, 2, '0'), 11.0000, '注', 50 - n, 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()
FROM (
  SELECT 1 n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10
  UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20
  UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25 UNION SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29 UNION SELECT 30
  UNION SELECT 31 UNION SELECT 32 UNION SELECT 33 UNION SELECT 34 UNION SELECT 35 UNION SELECT 36 UNION SELECT 37 UNION SELECT 38 UNION SELECT 39 UNION SELECT 40
  UNION SELECT 41 UNION SELECT 42 UNION SELECT 43 UNION SELECT 44 UNION SELECT 45 UNION SELECT 46 UNION SELECT 47 UNION SELECT 48 UNION SELECT 49
) t;

-- 平特 赔率 7.8
INSERT INTO `fa_acc_param` (`category_id`, `name`, `default_price`, `unit`, `weigh`, `status`, `createtime`, `updatetime`)
SELECT 3, LPAD(n, 2, '0'), 7.8000, '注', 50 - n, 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()
FROM (
  SELECT 1 n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10
  UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20
  UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25 UNION SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29 UNION SELECT 30
  UNION SELECT 31 UNION SELECT 32 UNION SELECT 33 UNION SELECT 34 UNION SELECT 35 UNION SELECT 36 UNION SELECT 37 UNION SELECT 38 UNION SELECT 39 UNION SELECT 40
  UNION SELECT 41 UNION SELECT 42 UNION SELECT 43 UNION SELECT 44 UNION SELECT 45 UNION SELECT 46 UNION SELECT 47 UNION SELECT 48 UNION SELECT 49
) t;

-- 平码 赔率 8.07
INSERT INTO `fa_acc_param` (`category_id`, `name`, `default_price`, `unit`, `weigh`, `status`, `createtime`, `updatetime`)
SELECT 4, LPAD(n, 2, '0'), 8.0700, '注', 50 - n, 1, UNIX_TIMESTAMP(), UNIX_TIMESTAMP()
FROM (
  SELECT 1 n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10
  UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20
  UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25 UNION SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29 UNION SELECT 30
  UNION SELECT 31 UNION SELECT 32 UNION SELECT 33 UNION SELECT 34 UNION SELECT 35 UNION SELECT 36 UNION SELECT 37 UNION SELECT 38 UNION SELECT 39 UNION SELECT 40
  UNION SELECT 41 UNION SELECT 42 UNION SELECT 43 UNION SELECT 44 UNION SELECT 45 UNION SELECT 46 UNION SELECT 47 UNION SELECT 48 UNION SELECT 49
) t;
